version: "3"

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env
    links:
      - mongodb

  mongodb:
    image: mongo
    hostname: "mongodb"
    container_name: "mongodb"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
    env_file:
      - .env
