version: '3'

services:
  backend:
    image: ${BACKEND_ECR_PATH}
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env
    links:
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
